

vpath kernel/%.s $(ARCH_DIR)
vpath kernel/%.c $(SOURCE_DIR) $(ARCH_DIR)

kernel.o: $(call std-dir,kernel,. sched init)

kernel.o:
	$(LD) -T$(SOURCE_DIR)/kernel/kernel.ld --relocatable -o $@ $^

kernel_s.o: kernel.o
	$(OBJCOPY) --strip-unneeded $^ $@


